name: Lottery Auto Buy

on:
  schedule:
    - cron: '0 4 * * 1' # 월요일 13:00 (KST)
    - cron: '0 13 * * 4' # 목요일 22:00 (KST)
    - cron: '5 13 * * 4' # 목요일 22:05 (KST)
  workflow_dispatch: # 수동 실행 가능

jobs:
  run_lotto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # [테스트] 수동 실행 시 로또 구매가 바로 동작하도록 설정
      - name: Run Lotto
        run: |
          python main.py --type lotto --manual "3,5,9,25,31,37" --count 4 --auto 1
        env:
          USER_ID: ${{ secrets.USER_ID }}
          USER_PW: ${{ secrets.USER_PW }}
